### ISSUE TITLE
Dont start

### ISSUE THREAD

**Issue by wat32** [little-brother/chupacabra#6]
~/cicada# node -v
v0.10.29
:~/cicada# node app.js

/root/cicada/app.js:2
const http = require('http');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by wat32** [comment]
~/cicada# git pull
Already up-to-date.

**Comment by little-brother** [comment]
Problem still exists?

Some versions may be broken, because the project increases functionality at the expense of stability.
