### ISSUE TITLE
Need Help  - Console Log Error

### ISSUE THREAD

**Issue by wruffin1** [little-brother/chupacabra#7]
DOMException: Failed to construct 'WebSocket': The URL 'ws://10.120.102.42:NaN' is invalid.
    at connect (http://10.120.102.42/node/NetworkMonitor/Public/events.js:14:13)
    at HTMLDocument.<anonymous> (http://10.120.102.42/node/NetworkMonitor/Public/events.js:49:2)
    at j (http://10.120.102.42/node/NetworkMonitor/Public/vendors/jquery-1.11.0.min.js:2:27136)
    at Object.fireWith [as resolveWith] (http://10.120.102.42/node/NetworkMonitor/Public/vendors/jquery-1.11.0.min.js:2:27949)
    at Function.ready (http://10.120.102.42/node/NetworkMonitor/Public/vendors/jquery-1.11.0.min.js:2:29783)
    at HTMLDocument.K (http://10.120.102.42/node/NetworkMonitor/Public/vendors/jquery-1.11.0.min.js:2:30128)
connect @ events.js:16
(anonymous) @ events.js:49
j @ jquery-1.11.0.min.js:2
fireWith @ jquery-1.11.0.min.js:2
ready @ jquery-1.11.0.min.js:2
K @ jquery-1.11.0.min.js:2
jquery-1.11.0.min.js:4 GET http://10.120.102.42/device 404 (Not Found)
send @ jquery-1.11.0.min.js:4
ajax @ jquery-1.11.0.min.js:4
(anonymous) @ app-device.js:26
j @ jquery-1.11.0.min.js:2
fireWith @ jquery-1.11.0.min.js:2
ready @ jquery-1.11.0.min.js:2
K @ jquery-1.11.0.min.js:2
jquery-1.11.0.min.js:4 GET http://10.120.102.42/diagram 404 (Not Found)

**Comment by little-brother** [comment]
Could you provide more details: browser name/version and OS? 

To quick fix:  edit `/public/events.js` line 14
`socket = new WebSocket('ws://' + location.hostname + ':' + (parseInt(location.port) + 1));`
to
`socket = new WebSocket('ws://' + location.hostname + ':' + 5001));`

**Comment by wruffin1** [comment]
Browser:  Google Chrome Version 66.0.3359.139 


OS :  Windows 7


Application resides on a server running Windows Server 2012
"
Also when try to run web application on my pc using my chrome I receive and Alert message:  "Websocket disabled: Failed to construct 'WebSocket': The URL 'ws://10.120.102.42:NaN' is invalid."






William S Ruffin
wruffin1@verizon.net




-----Original Message-----

**Comment by wruffin1** [comment]
I modified events.js line 14 as you suggested, now i am receiving this console log error message repeatly:

WebSocket connection to 'ws://10.120.102.42:5001/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
connect @ events.js:14
(anonymous) @ events.js:49
j @ jquery-1.11.0.min.js:2
fireWith @ jquery-1.11.0.min.js:2
ready @ jquery-1.11.0.min.js:2
K @ jquery-1.11.0.min.js:2
events.js:36 Wed May 02 2018 14:18:11 GMT-0400 (Eastern Daylight Time): Notify server is disconnected.

**Comment by little-brother** [comment]
Check Windows firewall. Ensure that 5000 and 5001 ports is unblocked. Look at [this tutor](https://youtu.be/cbFiWeeMUDI) to get more details.

**Comment by wruffin1** [comment]
THE PORTS ARE UNBLOCKED

I am now receiving theses errors

GET http://10.120.102.42/device 404 (Not Found)
send @ jquery-1.11.0.min.js:4
ajax @ jquery-1.11.0.min.js:4
(anonymous) @ app-device.js:26
j @ jquery-1.11.0.min.js:2
fireWith @ jquery-1.11.0.min.js:2
ready @ jquery-1.11.0.min.js:2
K @ jquery-1.11.0.min.js:2
jquery-1.11.0.min.js:4 GET http://10.120.102.42/diagram 404 (Not Found)
send @ jquery-1.11.0.min.js:4
ajax @ jquery-1.11.0.min.js:4
(anonymous) @ app-diagram.js:13
j @ jquery-1.11.0.min.js:2
fireWith @ jquery-1.11.0.min.js:2
ready @ jquery-1.11.0.min.js:2
K @ jquery-1.11.0.min.js:2
events.js:14 WebSocket connection to 'ws://10.120.102.42:5001/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
connect @ events.js:14
(anonymous) @ events.js:49
j @ jquery-1.11.0.min.js:2
fireWith @ jquery-1.11.0.min.js:2
ready @ jquery-1.11.0.min.js:2
K @ jquery-1.11.0.min.js:2
events.js:36 Wed May 02 2018 16:24:00 GMT-0400 (Eastern Daylight Time): Notify server is disconnected.
events.js:14 WebSocket connection to 'ws://10.120.102.42:5001/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
connect @ events.js:14
events.js:36 Wed May 02 2018 16:24:03 GMT-0400 (Eastern Daylight Time): Notify server is disconnected.
events.js:14 WebSocket connection to 'ws://10.120.102.42:5001/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
connect @ events.js:14
events.js:36 Wed May 02 2018 16:24:06 GMT-0400 (Eastern Daylight Time): Notify server is disconnected.
events.js:14 WebSocket connection to 'ws://10.120.102.42:5001/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
connect @ events.js:14
events.js:36 Wed May 02 2018 16:24:09 GMT-0400 (Eastern Daylight Time): Notify server is disconnected.
events.js:14 WebSocket connection to 'ws://10.120.102.42:5001/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
connect @ events.js:14
events.js:36 Wed May 02 2018 16:24:12 GMT-0400 (Eastern Daylight Time): Notify server is disconnected.

**Comment by little-brother** [comment]
`http://10.120.102.42/device` a some strange request. It must be `http://10.120.102.42:5000/device`

Could you check via Firefox or Edge? It's look like that Chrome ignores `location.port`.
I also use Win7/Chrome but don't have any problem with connection.

**Comment by wruffin1** [comment]
Need Help - I have it installed on my server and it works fine using any browser on my server adding 127.0.0.1:5000 in my address field.  When i try to access the application from a client browser it fails can't find /device and /diagram both have an error of 404

**Comment by little-brother** [comment]
Check ports again. On client machine run `telnet 10.120.102.42 5000` and `telnet 10.120.102.42 5001`. If the port is closed, a warning will be displayed. Here [more details](https://stackoverflow.com/a/16230168/6121703).

**Comment by wruffin1** [comment]
Got it, that works great.  How do you access the  port from http when you have no access to the command prompt on the server ?

**Comment by little-brother** [comment]
These commands only check the ports, and do not access it.
From mobile devices, you can check open ports using [special programs](http://appcrawlr.com/app/search?q=port+scanner&device=ios&price=Free).
